#ifndef TELEGRAM_CONFIG_H_INCLUDED
#define TELEGRAM_CONFIG_H_INCLUDED

#define BOOST_SYSTEM_NO_DEPRECATED
//#define BOOST_ASIO_NO_DEPRECATED

#define BOOST_SYSTEM_NO_LIB
#define BOOST_ERROR_CODE_HEADER_ONLY
#define URDL_HEADER_ONLY 1

#define BOOST_CGI_NO_BOOST_FILESYSTEM

#ifdef LIBTELEGRAM_DISABLE_SSL_NO_REALLY_I_MEAN_IT_AND_I_KNOW_WHAT_IM_DOING
  #warning "SSL is disabled for outgoing messages - that is such a bad idea."
  #define URDL_DISABLE_SSL 1
  #define LIBTELEGRAM_OUTGOING_PROTO "http"
#else
  #define LIBTELEGRAM_OUTGOING_PROTO "https"
#endif // LIBTELEGRAM_DISABLE_SSL_NO_REALLY_I_MEAN_IT_AND_I_KNOW_WHAT_IM_DOING

#endif // TELEGRAM_CONFIG_H_INCLUDED
